package oracle.mybatis01;

/*
 * 
 * Java 오브젝트에 매핑!
 * 
 */



// 참고 : https://araikuma.tistory.com/472
// 기본 Mapper 만들기
//  autogenerated-key 받아오기

// IN(a, b, c ) 등의 코드 만들기  --> 나중에

public class Mabatis01Main {

	public static void main(String[] args) {
		System.out.println("MyBatis 사용");
		
		
		System.out.println("\n프로그램 종료");
	} // end main()

} // end class

